# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # full_body.launch.py
    ocs2_wbc_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    # split_body.launch.py
    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    head_joint_controller:
      type: basic_joint_controller/BasicJointController

    body_joint_controller:
      type: basic_joint_controller/BasicJointController

ocs2_wbc_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 50  # Hz
    mpc_frequency: 25
    info_file_name: task
    joints:
      - body_joint1
      - body_joint2
      - body_joint3
      - body_joint4
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: ai2_bot2
    home_duration: 2.0

    # Control parameters
    home_1: [
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -0.0003,
      0.0,
      0.0,
      0.0,
      0.0,
      -0.0002,
      0.0,
      -0.0003,
      0.0,
      0.0,
      0.0,
      0.0,
      -0.0002
    ]
    # Control parameters
    home_2: [
      -1.2868,
      2.7576,
      -1.5708,
      -0.0300,
      0.8333,
      0.0,
      0.0,
      -1.7800,
      0.0,
      -0.6410,
      0.0,
      -0.8333,
      0.0,
      0.0,
      -1.7800,
      0.0,
      -0.6410,
      0.0
    ]


ocs2_arm_controller:
  ros__parameters:
    update_rate: 50  # Hz
    mpc_frequency: 25
    info_file_name: split
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: ai2_bot2
    home_duration: 2.0

    home_1: [
      0.0, -0.0003, 0.0, 0.0, 0.0, 0.0, -0.0002,
      0.0, -0.0003, 0.0, 0.0, 0.0, 0.0, -0.0002
    ]
    home_2: [
      0.8333,
      0.0,
      0.0,
      -1.7800,
      0.0,
      -0.6410,
      0.0,
      -0.8333,
      0.0,
      0.0,
      -1.7800,
      0.0,
      -0.6410,
      0.0
    ]


head_joint_controller:
  ros__parameters:
    update_rate: 50  # Hz

    joints:
      - head_joint1
      - head_joint2

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    home_1: [ 0.0, 0.0 ]
    home_2: [ 0.0, -0.1 ]

    home_duration: 2.0
    movej_duration: 2.0
    hold_position_threshold: 0.1


body_joint_controller:
  ros__parameters:
    update_rate: 50  # Hz

    joints:
      - body_joint1
      - body_joint2
      - body_joint3
      - body_joint4

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    home_1: [ 0.0, 0.0, 0.0, 0.0 ]

    home_duration: 3.0
    movej_duration: 3.0
    hold_position_threshold: 0.05


left_gripper_controller:
  ros__parameters:
    joint: left_gripper_joint

right_gripper_controller:
  ros__parameters:
    joint: right_gripper_joint
