<?xml version="1.0"?>
<package format="2">
  <name>cobot_magic_v2_description</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for AgileX Cobot Magic V2 (Mobile Aloha V2)</p>
    <p>Tracer / Tracer V2 chassis + dual Piper arms (piper/h/l/x) + gripper or BrainCo Revo.</p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com"/>

  <license>BSD</license>
  <depend>piper_description</depend>
  <depend>brainco_description</depend>
  <depend>sensor_models</depend>
  <exec_depend>robot_common_launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
