# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController


arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

hand_controller:
  ros__parameters:
    joint: gripper_joint

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 50  # Hz
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: panthera

    # Control parameters
    home_pos: [0.0, 0.594, 0.306, 0.331, 0.0, 0.0]
    zero_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]