# This config file of OpenArm Bimanual is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      # type: adaptive_gripper_controller/AdaptiveGripperController
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  
hand_controller:
  ros__parameters:
    # 基本夹爪参数
    joints: 
      - left_gripper_joint
      - right_gripper_joint
    # 力反馈阈值参数
    # force_threshold: 0.1  # 力阈值（牛顿），超过此值将停止夹取

# 关节状态广播器配置
# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - left_gripper_joint
#       - right_gripper_joint

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 50  # Hz
    info_file_name: task
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position
    future_time_offset: 2.0

    robot_name: openarm
    robot_type: "bimanual"

    # Control parameters
    home_pos: [ 0.0, 0.594, 0.306, 0.331, 0.0, 0.0, 0.0,
                0.0, 0.594, 0.306, 0.331, 0.0, 0.0, 0.0 ]
    rest_pos: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

  