# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_wbc_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    head_joint_controller:
      type: basic_joint_controller/BasicJointController

    left_gripper_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    right_gripper_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

ocs2_wbc_controller:
  ros__parameters:
    update_rate: 100
    mpc_frequency: 50
    info_file_name: fixed_base

    joints:
      - body_joint1
      - body_joint2
      - body_joint3
      - body_joint4
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: galbot_one
    home_interpolation_type: linear
    # home: low standing posture (between upright and squat), arms relatively open
    home_1: [ 0.5825795598426468, 1.4997342332792214, 0.8621225208206932, 0.007935824653415023,
              1.88, 1.35, 0.0, -1.23, 0.0, -0.19, 0.0,
              -1.88, 1.35, 0.0, 1.23, 0.0, 0.19, 0.0 ]
    # rest: full squat posture, arms folded closer to body
    home_2: [ 0.0, 0.0, 0.0, 0.0,
              3.1415,  1.57,  0.0, -2.1, 0.0, -1.0, 0.0,
              -3.1415,  1.57, 0.0, 2.1, 0.0, 1.0, 0.0 ]

head_joint_controller:
  ros__parameters:
    update_rate: 100
    joints:
      - head_joint1
      - head_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    home_1: [ 0.0, 0.0 ]
    home_2: [ 0.0, -0.1 ]
    home_duration: 2.0
    movej_duration: 2.0
    hold_position_threshold: 0.1

left_gripper_controller:
  ros__parameters:
    joint: left_gripper_joint
    joints:
      - left_gripper_joint
    use_effort_interface: false

right_gripper_controller:
  ros__parameters:
    joint: right_gripper_joint
    joints:
      - right_gripper_joint
    use_effort_interface: false
