# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 500  # Hz
    mpc_frequency: 100
    info_file_name: task
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

    left_ee_name: "left_hand_base"
    right_ee_name: "right_hand_base"

    default_gains: [ 60.0,2.0 ]
    ocs2_gains: [ 100.0,4.0 ]

    command_interfaces:
      - position
      - velocity
      - effort
      - kp
      - kd
    state_interfaces:
      - position
      - velocity
      - effort

    robot_name: unitree_g1
    home_duration: 5.0
    movel_trajectory_duration: 6.0
    movej_interpolation_type: doubles
    home_interpolation_type: doubles

    # Control parameters
    # home_pos: [left_shoulder_pitch, left_shoulder_roll, left_shoulder_yaw, left_elbow, left_wrist_roll, left_wrist_pitch, left_wrist_yaw,
    #            right_shoulder_pitch, right_shoulder_roll, right_shoulder_yaw, right_elbow, right_wrist_roll, right_wrist_pitch, right_wrist_yaw]
    home_pos: [
      0.0, 0.2, 0.0, 0.0, -0.2, 0.0, 0.0,
      0.0, -0.2, 0.0, 0.0, 0.2, 0.0, 0.0 ]
    # rest_pos: [left_shoulder_pitch, left_shoulder_roll, left_shoulder_yaw, left_elbow, left_wrist_roll, left_wrist_pitch, left_wrist_yaw,
    #            right_shoulder_pitch, right_shoulder_roll, right_shoulder_yaw, right_elbow, right_wrist_roll, right_wrist_pitch, right_wrist_yaw]
    rest_pos: [
      0.0, 0.2, 0.0, 1.57, 0.0, 0.0, 0.0,
      0.0, -0.2, 0.0, 1.57, 0.0, 0.0, 0.0 ]