<?xml version="1.0"?>
<package format="2">
  <name>agilex_aloha_description</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for AgileX Mobile Aloha2 (V2)</p>
    <p>Tracer chassis + dual Piper arms. Split Aloha lives in split_aloha_description.
    </p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com"/>

  <license>BSD</license>
  <depend>piper_description</depend>
  <depend>brainco_description</depend>
  <depend>sensor_models</depend>
  <exec_depend>robot_common_launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>